name: UPSC AI News Agent

on:
  workflow_dispatch:

  schedule:
    # TEST: 12:10 PM IST = 6:40 AM UTC
    - cron: "40 6 * * *"

jobs:
  fetch-analyze-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      - name: Run UPSC AI News Agent
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python upsc_agent.py
